# Generated by Django 3.0.6 on 2020-05-12 16:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='statistics',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
