# Generated by Django 3.0.6 on 2020-05-12 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import shortener.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, validators=[shortener.validators.validate_url])),
                ('shortcode', models.CharField(blank=True, max_length=15, unique=True)),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime(2020, 5, 12, 15, 48, 31, 440098, tzinfo=utc))),
                ('date_of_expiry', models.DateTimeField(default=datetime.datetime(2021, 5, 12, 15, 48, 31, 440098, tzinfo=utc))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
