# Generated by Django 3.0.6 on 2020-05-12 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20200512_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 16, 20, 10, 818044, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 16, 20, 10, 818044, tzinfo=utc)),
        ),
    ]
