# Generated by Django 3.0.6 on 2020-05-13 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20200513_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 11, 41, 8, 342531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 11, 41, 8, 342531, tzinfo=utc)),
        ),
    ]
