# Generated by Django 3.0.6 on 2020-05-16 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20200516_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 16, 33, 42, 637368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 16, 33, 42, 637368, tzinfo=utc)),
        ),
    ]
