# Generated by Django 3.0.6 on 2020-05-17 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0009_auto_20200516_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 9, 34, 31, 611120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 9, 34, 31, 611120, tzinfo=utc)),
        ),
    ]
